### ISSUE TITLE
All-in-one archetype does not work with SDK 1.1.1, SOLR and Alfresco version 4.1.2 - 4.1.5

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#180]
_From [marco.ma...@gmail.com](https://code.google.com/u/100510182668835413952/) on March 03, 2014 08:29:36_

What steps will reproduce the problem? 1. Create a new maven project with All-in-one archetype
2. Change the pom.xml of the main project using the following properties
   <alfresco.groupId>org.alfresco.enterprise</alfresco.groupId>
   <alfresco.version>4.1.2</alfresco.version>
1. Add the private repository:
          <repository>
           <id>alfresco-private-repository</id>
           <url> https://artifacts.alfresco.com/nexus/content/groups/private</url> </repository>
2. Perform a mvn install -Prun

What is the expected output? 
Alfresco should run without errors

What do you see instead?
Error in the alfresco.log

2014-03-03 12:51:42,480  ERROR [solr.core.CoreContainer] [localhost-startStop-1] org.apache.solr.common.SolrException: Error loading class 'org.alfresco.solr.ArrayListCache'
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:375)
    at org.apache.solr.search.CacheConfig.getConfig(CacheConfig.java:98)
    at org.apache.solr.search.CacheConfig.getMultipleConfigs(CacheConfig.java:73)
    at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:164)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:405)
    at org.apache.solr.core.CoreContainer.load(CoreContainer.java:278)
    at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:117)
    at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:83)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4656)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5309)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: org.alfresco.solr.ArrayListCache
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:266)
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:359)
    ... 20 more

2014-03-03 12:51:42,656  ERROR [solr.core.CoreContainer] [localhost-startStop-1] org.apache.solr.common.SolrException: Error loading class 'org.alfresco.solr.ArrayListCache'
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:375)
    at org.apache.solr.search.CacheConfig.getConfig(CacheConfig.java:98)
    at org.apache.solr.search.CacheConfig.getMultipleConfigs(CacheConfig.java:73)
    at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:164)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:405)
    at org.apache.solr.core.CoreContainer.load(CoreContainer.java:278)
    at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:117)
    at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:83)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4656)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5309)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: org.alfresco.solr.ArrayListCache
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:266)
    at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:359)
    ... 20 more

Solr is not working, any search in Share won't any return results

What version of the product are you using? 
SDK 1.1.1
- All-in-one archetype
- Alfresco version 4.1.2, 4.1.3,4.1.4 ( error shown at point 3)
- Alfresco 4.1.5 different error but SOLR still not working:

2014-03-03 13:17:15,003  ERROR [solr.tracker.CoreTracker] [SolrTrackerScheduler_Worker-3] Tracking failed
org.alfresco.error.AlfrescoRuntimeException: 02030011 GetModelsDiff return status is 302
    at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1059)
    at org.alfresco.solr.tracker.CoreTracker.trackModels(CoreTracker.java:1875)
    at org.alfresco.solr.tracker.CoreTracker.trackRepository(CoreTracker.java:1205)
    at org.alfresco.solr.tracker.CoreTracker.updateIndex(CoreTracker.java:491)
    at org.alfresco.solr.tracker.CoreTrackerJob.execute(CoreTrackerJob.java:45)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)
2014-03-03 13:17:24,643  ERROR [solr.core.SolrCore] [http-bio-8080-exec-3] java.lang.NullPointerException
    at org.alfresco.repo.search.impl.lucene.query.RelativeStructuredFieldPosition.<init>(RelativeStructuredFieldPosition.java:38)
    at org....

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=180_

**Comment by jgoldhammer** [comment]
Due to the age of this issue, I will close the ticket. The interest of supporting older versions than Alfresco 4.2 should be very low in my point of view. If anybody feels, the SDK should support older versions, please create a new ticket with specific requirements.
