### ISSUE TITLE
When running all-in-one archetype from maven under windows the Win32NetBIOSx64.dll is missing preventing cifs working properly.

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#193]
_From [colum...@gmail.com](https://code.google.com/u/100251676538566683892/) on July 03, 2014 10:00:03_

When running all-in-one archetype from maven under windows the Win32NetBIOSx64.dll is missing preventing cifs working properly.

How to reproduce?

2) create a all-in-one projectusing
mvn archetype:generate -DarchetypeCatalog= https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml -Dfilter=org.alfresco.maven.archetype:

Select option 2

2) Modify the generated root pom.xml and specify version 4.1.5 (<alfresco.version>4.1.5</alfresco.version>), also configure access to private repository.

3)Run the project: mvn install -Prun
Observed result, the exception under is thrown and cifs does not work properly:

2014-06-04 10:55:35,310 ERROR [org.alfresco.fileserver] [localhost-startStop-1] java.lang.UnsatisfiedLinkError: no Win32NetBIOSx64 in java.library.path 
2014-06-04 10:55:35,312 ERROR [org.alfresco.fileserver] [localhost-startStop-1] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886) 
2014-06-04 10:55:35,313 ERROR [org.alfresco.fileserver] [localhost-startStop-1] at java.lang.Runtime.loadLibrary0(Runtime.java:849) 
2014-06-04 10:55:35,315 ERROR [org.alfresco.fileserver] [localhost-startStop-1] at java.lang.System.loadLibrary(System.java:1088) 
2014-06-04 10:55:35,316 ERROR [org.alfresco.fileserver] [localhost-startStop-1] at org.alfresco.jlan.netbios.win32.Win32NetBIOS.<clinit>(Win32NetBIOS.java:834) 

Hint:
After setting the folder containing the dll in the PATH while executing problem was gone but it should be done automatically under windows.

_Original issue: http://code.google.com/p/maven-alfresco-archetypes/issues/detail?id=193_

**Comment by ohej** [comment]
An old issue related back to SDK 1.x and ACS 4.1.x. Closing the issue.
