### ISSUE TITLE
Issues running JUnit tests against SDK 1.2-SNAPSHOT All-in-one

### ISSUE THREAD

**Issue by hagak** [Alfresco/alfresco-sdk#235]
Using SDK 1.2 with Alfresco 4.2.3.3.
First tested with my projects unit tests that use solr queries and I got a stack trace below: That is basically complaing that it can not connect to solr.   Note that I had already changed my env to use MySQL since solr did not play well with H2.  Below is just a snippet of the stack trace:
<code>
org.alfresco.repo.search.impl.lucene.LuceneQueryParserException: 10110012
at org.alfresco.repo.search.impl.solr.SolrQueryHTTPClient.executeQuery(SolrQueryHTTPClient.java:501)
Caused by: java.net.ConnectException: Connection refused: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
at sun.security.ssl.SSLSocketImpl.(SSLSocketImpl.java:451)
at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:140)
at org.alfresco.encryption.ssl.AuthSSLProtocolSocketFactory.createSocket(AuthSSLProtocolSocketFactory.java:168)
at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
at org.alfresco.repo.search.impl.solr.SolrQueryHTTPClient.executeQuery(SolrQueryHTTPClient.java:445)
</code>

So I decided to step back to just a basic all-in-one SDK 1.2 with no changes except adding the Demo unit test from the AMP package since the all-in-one does not include a sample unit test.
When I run mvn install -Prun against it I get the following:
<code>
Running org.alfresco.demoamp.test.DemoComponentTest
SDK Demo AMP class has been loaded
Server running at http://localhost:4578
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 39.716 sec <<< FAILURE! - in org.alfresco.demoamp.test.DemoComponentTest
testChildNodesCount(org.alfresco.demoamp.test.DemoComponentTest)  Time elapsed: 38.451 sec  <<< ERROR!
java.lang.NullPointerException: null
    at org.alfresco.demoamp.DemoComponent.getCompanyHome(DemoComponent.java:65)
    at org.alfresco.demoamp.test.DemoComponentTest.testChildNodesCount(DemoComponentTest.java:79)

testGetCompanyHome(org.alfresco.demoamp.test.DemoComponentTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
    at org.alfresco.demoamp.DemoComponent.getCompanyHome(DemoComponent.java:65)
    at org.alfresco.demoamp.test.DemoComponentTest.testGetCompanyHome(DemoComponentTest.java:69)

Could not start JUnit remoteServer
</code>

**Comment by jgoldhammer** [comment]
Due to the age of this issue, I will close the ticket. The new SDK 3 will provide the possibility to start SOLR in a repo/aio project. @hagak - if you think different, please reopen the ticket.
