### ISSUE TITLE
v2 beta 4 AMP build archetype - integration-test amp-to-war - mysql components are missing

### ISSUE THREAD

**Issue by SteveCOS** [Alfresco/alfresco-sdk#237]
I’m running v2 beta 4 beta AMP build archetype and get errors when trying to run integration-test amp-to-war. Message in Eclipse console always says that mysql components are missing even though I have not made any changes to the default configuration. I am expecting it to run H2 by default.

**********************************************
… 93 more
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.repo.domain.schema.DataSourceCheck]: Constructor threw exception; nested exception is java.lang.RuntimeException: Database connection failed: Cannot load JDBC driver class ‘org.gjt.mm.mysql.Driver’
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:108)
at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
… 104 more
Caused by: java.lang.RuntimeException: Database connection failed: Cannot load JDBC driver class ‘org.gjt.mm.mysql.Driver’
at org.alfresco.repo.domain.schema.DataSourceCheck.(DataSourceCheck.java:59)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:126)
… 106 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class ‘org.gjt.mm.mysql.Driver’
at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
at org.alfresco.repo.domain.schema.DataSourceCheck.(DataSourceCheck.java:53)
… 111 more
Caused by: java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1713)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1420)
… 114 more

Oct 21, 2014 2:27:39 PM com.sun.xml.ws.transport.http.servlet.WSServletContextListener contextInitialized
INFO: WSSERVLET12: JAX-WS context listener initializing
Oct 21, 2014 2:27:46 PM com.sun.xml.ws.transport.http.servlet.WSServletDelegate
INFO: WSSERVLET14: JAX-WS servlet initializing
Oct 21, 2014 2:27:46 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Oct 21, 2014 2:27:46 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/alfresco] startup failed due to previous errors
Oct 21, 2014 2:27:46 PM com.sun.xml.ws.transport.http.servlet.WSServletDelegate destroy
INFO: WSSERVLET15: JAX-WS servlet destroyed
Oct 21, 2014 2:27:46 PM com.sun.xml.ws.transport.http.servlet.WSServletContextListener contextDestroyed
INFO: WSSERVLET13: JAX-WS context listener destroyed
Oct 21, 2014 2:27:46 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Oct 21, 2014 2:27:46 PM org.apache.catalina.core.ApplicationContext log
INFO: Shutting down log4j
Oct 21, 2014 2:27:46 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6dd1f5aa]) and a value of type [org.apache.cxf.bus.CXFBusImpl] (value [org.apache.cxf.bus.CXFBusImpl@7357a439]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 21, 2014 2:27:46 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/alfresco] created a ThreadLocal with key of type [com.sun.xml.bind.v2.ClassFactory$1] (value [com.sun.xml.bind.v2.ClassFactory$1@4386be8a]) and a value of type [java.util.WeakHashMap] (value [{class javax.xml.bind.annotation.W3CDomHandler=java.lang.ref.WeakReference@6ce82fb5}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Oct 21, 2014 2:27:46 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
 ** per previous post on mindthegab.com

**Comment by mindthegab** [comment]
This functionality works in 2.0.0 and 2.1.0, when environment is properly configured.
