### ISSUE TITLE
Non fatal ERROR in logs ERROR [domain.schema.SchemaBootstrap] [main] Unable to validate database schema.

### ISSUE THREAD

**Issue by mindthegab** [Alfresco/alfresco-sdk#250]
This error happens on db initialization / startup of alfresco both in mvn test and run embedded. Probably related to the usage of h2 dialect, but needs to be investigated further

Full log below:

2014-12-23 16:16:09,850  ERROR [domain.schema.SchemaBootstrap] [main] Unable to validate database schema.
 java.lang.IllegalArgumentException: dbObject cannot be null.
	at org.alfresco.util.schemacomp.DbProperty.<init>(DbProperty.java:51)
	at org.alfresco.util.schemacomp.DbProperty.<init>(DbProperty.java:113)
	at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:175)
	at org.alfresco.util.schemacomp.model.Table.doDiff(Table.java:220)
	at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:178)
	at org.alfresco.util.schemacomp.DefaultComparisonUtils.compareCollections(DefaultComparisonUtils.java:208)
	at org.alfresco.util.schemacomp.model.Schema.doDiff(Schema.java:181)
	at org.alfresco.util.schemacomp.model.AbstractDbObject.diff(AbstractDbObject.java:178)
	at org.alfresco.util.schemacomp.SchemaComparator.compare(SchemaComparator.java:66)
	at org.alfresco.util.schemacomp.SchemaComparator.validateAndCompare(SchemaComparator.java:57)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.attemptValidateSchema(SchemaBootstrap.java:1920)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.validateSchema(SchemaBootstrap.java:1862)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.validateSchema(SchemaBootstrap.java:1849)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.onBootstrap(SchemaBootstrap.java:1749)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:209)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:180)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:84)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:280)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:304)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:211)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at com.tradeshift.test.remote.RemoteTestRunner.run(RemoteTestRunner.java:73)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by mindthegab** [comment]
This is being worked by @gravitonian at https://issues.alfresco.com/jira/browse/DEVPLAT-3

**Comment by gravitonian** [comment]
Fixed, see: https://issues.alfresco.com/jira/browse/DEVPLAT-3
