### ISSUE TITLE
H2Dialect upgrade scripts not copied

### ISSUE THREAD

**Issue by loftux** [Alfresco/alfresco-sdk#259]
Since the commit 58ee1a3c79f44b10d22395a2c8a78b0e0b653b36 (move of H2Dialect resource copy from alfresco-parent-sdk pom to alfresco-rad pom) the resources are not copied.

How to reproduce:
 - Create an alfresco-amp project using the archetype generator
 - Add in pom.xml <properties> the entry <alfresco.version>5.0.c</alfresco.version>
 - Start once `mvn integration-test`, all is started fine.
 - Change version to <alfresco.version>5.1-SNAPSHOT</alfresco.version>
 - Start again 'mvn clean integration-test`
Expected: The upgrade of the current H2 database in alf_data_dev to be upgraded (or at least try to)
Actual: Sql scripts missing

If you add back to the project pom what was removed from alfresco-parent-sdk in the referenced commit the scripts try to run (but fails due to sql errors). Thats another issue I think.

**Comment by gravitonian** [comment]
Hi,

Can you build the SDK locally and test with latest changes and see if it solves your problem.

**Comment by ohej** [comment]
This issue still persists. Steps to reproduce:
1. Generate repo-amp project
2. Change alfresco version to 5.0.c
3. ./run.sh and let it start
4.  Change version to 5.0.d and run ./run.sh again

Output:
``
Jun 08, 2015 9:22:11 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.alfresco.web.app.ContextListener
org.alfresco.error.AlfrescoRuntimeException: 05080001 Schema auto-update failed
	at org.alfresco.repo.domain.schema.SchemaBootstrap.onBootstrap(SchemaBootstrap.java:1801)
	at org.springframework.extensions.surf.util.AbstractLifecycleBean.onApplicationEvent(AbstractLifecycleBean.java:56)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:209)
	at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:180)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.alfresco.web.app.ContextLoaderListener.configureAndRefreshWebApplicationContext(ContextLoaderListener.java)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.alfresco.web.app.ContextLoaderListener.initWebApplicationContext(ContextLoaderListener.java)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.error.AlfrescoRuntimeException: 05080000 Script [ classpath:alfresco/dbscripts/upgrade/4.2/${db.script.dialect}/migrate-locale-multilingual.sql ] can't be found for class org.hibernate.dialect.H2Dialect
	at org.alfresco.repo.domain.schema.SchemaBootstrap.getScriptInputStream(SchemaBootstrap.java:1205)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.executeScriptUrl(SchemaBootstrap.java:1116)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.checkSchemaPatchScripts(SchemaBootstrap.java:1108)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.updateSchema(SchemaBootstrap.java:973)
	at org.alfresco.repo.domain.schema.SchemaBootstrap.onBootstrap(SchemaBootstrap.java:1702)
	... 21 more
``

**Comment by gravitonian** [comment]
I think it works if you delete alf_data_dev. Should maybe rename to H2 database upgrade does not work.

**Comment by ohej** [comment]
Yes, by deleting alf_data_dev it works fine, so it is indeed the upgrade scripts that are causing the issues

**Comment by mindthegab** [comment]
This is not an SDK issue, more of an issue with the upgrade scripts playing nicely with H2. Workaround is to remove alf_data_dev when changing versions.
