### ISSUE TITLE
Start of alfresco repo fails by using amp-to-war with mysql driver not found exception...

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#263]
I try to change the js-console-repo project to update to alfresco-sdk-2.0, but I have following exception.

```java

Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.repo.domain.schema.DataSourceCheck]: Constructor threw exception; nested exception is java.lang.RuntimeException: Database c
l.Driver'
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:277)
        ... 128 more
Caused by: java.lang.RuntimeException: Database connection failed: Cannot load JDBC driver class 'org.gjt.mm.mysql.Driver'
        at org.alfresco.repo.domain.schema.DataSourceCheck.<init>(DataSourceCheck.java:59)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
        ... 130 more
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class 'org.gjt.mm.mysql.Driver'
        at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
        at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at org.alfresco.repo.domain.schema.DataSourceCheck.<init>(DataSourceCheck.java:53)
        ... 135 more
Caused by: java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
        at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1420)
        ... 138 more

```

Thanks,
Jens

**Comment by jgoldhammer** [comment]
Using following pom.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
   
    <groupId>org.sharextras</groupId>
    <artifactId>javascript-console-repo</artifactId>
    <version>0.6.0</version>
    <name>JavaScript Console - Repository</name>
    <description>Alfresco Share-Extras JavaScript Console - Repository Module</description>
    <packaging>amp</packaging>
	
	<parent>
        <groupId>org.alfresco.maven</groupId>
        <artifactId>alfresco-sdk-parent</artifactId>
        <version>2.0.0</version>
    </parent>

	
    <developers>
        <developer>
            <id>f.maul</id>
            <name>Florian Maul</name>
            <email>f.maul@fme.de</email>
            <organization>fme AG</organization>
            <roles>
                <role>Founder</role>
                <role>Architect</role>
                <role>Developer</role>
            </roles>
            <properties>
                <twitter>twitter.com/fmaul</twitter>
            </properties>
        </developer>
    </developers>

    <!-- 
       | SDK properties have sensible defaults in the SDK parent,
       | but you can override the properties below to use another version. 
       | For more available properties see the alfresco-sdk-parent POM. 
       -->
    <properties>
        <!--
            | Defines the groupId for the Alfresco Artifacts to work against. As of 4.2 the only allowed value is: org.alfresco
            | NOTE: See http://docs.alfresco.com/4.2/concepts/dev-extensions-maven-sdk-tutorials-alfresco-enterprise.html for details
        -->
        <!-- <alfresco.groupId>org.alfresco</alfresco.groupId> -->
        <!-- Defines the Alfresco version to work against.
             Community versions are typically identified by major.minor.character (4.2.a) while Enterprise versions are identified by major.minor.digit (4.2.0)  -->
        <!-- <alfresco.version>5.0.c</alfresco.version>-->
        <app.log.root.level>ERROR</app.log.root.level>
        <alfresco.data.location>alf_data_dev</alfresco.data.location>
        <!-- This controls which properties will be picked in src/test/properties for embedded run -->
        <env>local</env>
        <!-- Defines the target WAR artifactId to run this amp, only used with the -Pamp-to-war profile
             | Defaults to a vanilla repository AMP, but could point to your foundation / aggregator WAR 
        .    | Allowed values for Community: alfresco | share
             | Allowed values for Enterprise: alfresco-enterprise | share-enterprise
             <alfresco.client.war>${alfresco.repo.artifactId}</alfresco.client.war> -->
        <!-- Context path to run alfresco on -->
        <alfresco.client.contextPath>/alfresco</alfresco.client.contextPath>
        <!-- Defines the target WAR groupId to run this amp, only used with the -Pamp-to-war switch
        .    | Could be org.alfresco or your corporate groupId -->
        <!-- <alfresco.client.war.groupId>${alfresco.groupId}</alfresco.client.war.groupId> -->
        
        <!-- Defines the target WAR version to run this amp, only used with the -Pamp-to-war switch -->
        <!-- <alfresco.client.war.version>${alfresco.version}</alfresco.client.war.version>-->
    </properties>

    <!-- Here we realize the connection with the Alfresco selected platform (e.g.version and edition) -->
    <dependencyManagement>
        <dependencies>
            <!-- This will import the dependencyManagement for all artifacts in the selected Alfresco version/edition (see http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies)
                NOTE: You still need to define dependencies in your POM, but you can omit version as it's enforced by this dependencyManagement. NOTE: It defaults
                to the latest version this SDK pom has been tested with, but alfresco version can/should be overridden in your project's pom -->
            <dependency>
                <groupId>${alfresco.groupId}</groupId>
                <artifactId>alfresco-platform-distribution</artifactId>
                <version>${alfresco.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- Following dependencies are needed for compiling Java code in src/main/java; <scope>provided</scope> is inherited for each of the following;
        for more info, please refer to alfresco-platform-distribution POM -->
    <dependencies>
        <dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
        </dependency>
    </dependencies>


    <profiles>

    
		
		<!-- Enterprise profile, manually activated, automatically adds support for Enterprise edition development (dependencies) -->
        <profile>
            <id>enterprise</id>
            <dependencies>
                <dependency>
                    <groupId>${alfresco.groupId}</groupId>
                    <artifactId>alfresco-enterprise-repository</artifactId>
                    <version>${alfresco.version}</version>
                    <scope>provided</scope>
                </dependency>
            </dependencies>
        </profile>

    </profiles>

</project>
```

**Comment by jgoldhammer** [comment]
Everything works now- just a problem that I have missed some entries in context.xml...
