### ISSUE TITLE
Spring loaded does not work reliably with Rhino / FME JS Console

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#296]
After testing the new Alfresco SDK 2.1 release (which is really awesome), I have noticed that spring reloaded is not really reliable. After making some small changes in Java Code (adding an try finally block), spring reloaded breaks the running object instances, so that calls to that reloaded code does not work anymore (worse than the builtin hot reload capabilities of JVM).

Example:
```java
Caused by: java.lang.IllegalAccessError: tried to access method org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(Ljava/lang/Throwable;Lorg/springframework/extensions/webscripts/WebScriptRequest;Lorg/springframework/extensions/webscripts/WebScriptResponse;)Lorg/spring
framework/extensions/webscripts/WebScriptException; from class de.fme.jsconsole.ExecuteWebscript$$EPEBJ3eC
        at de.fme.jsconsole.ExecuteWebscript$$EPEBJ3eC.executeScriptContent(ExecuteWebscript.java:433)
        at de.fme.jsconsole.ExecuteWebscript$$EPEBJ3eC.access$1(ExecuteWebscript.java:331)
        at de.fme.jsconsole.ExecuteWebscript$$DPEBJ3eC.access$1(Unknown Source)
        at de.fme.jsconsole.ExecuteWebscript.access$1(ExecuteWebscript.java)
        at de.fme.jsconsole.ExecuteWebscript$2$$EPEBJ3dx.execute(ExecuteWebscript.java:313)
        at de.fme.jsconsole.ExecuteWebscript$2$$DPEBJ3dx.execute(Unknown Source)
        at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java)
        at de.fme.jsconsole.ExecuteWebscript$2$$EPEBJ3dx.execute(ExecuteWebscript.java:1)
        at de.fme.jsconsole.ExecuteWebscript$2$$DPEBJ3dx.execute(Unknown Source)
        at de.fme.jsconsole.ExecuteWebscript$2.execute(ExecuteWebscript.java)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
        ... 46 more

```

I would prefer JRebel to have a working solution. 

Reasons:
* Spring Reloaded is only maintained by a few people and is a not very active project- please see the github commit log (https://github.com/spring-projects/spring-loaded/commits/master)
* JRebel is very popular in the community- it just works.

Environment:
* Alfresco 5.0.d
* JDK 1.8
* Alfresco SDK 2.1
* Windows 7
* springreloaded 1.2.3

**Comment by mindthegab** [comment]
Hi @jgoldhammer,

thanks for the feedback ;)

Nevertheless I suggest you keep a bug report separate from a feature request. I.e. let's keep this open and raise a separate issue if you want an improved Jrebel support. This issue itself doesn't prove / provide much data about spring-loaded being generally unreliable.

BTW, there is (deprecated) support for Jrebel in the SDK (see  -Pjrebel https://github.com/Alfresco/alfresco-sdk/blob/master/poms/alfresco-sdk-parent/pom.xml#L1041), since it was the first implementation. But, being a closed source/non free/non redistributable technology, we made the choice to move out of it. You can certainly welcome to use Jrebel with the SDK, but if you want a better integration can you please raise a separate issue and specify how would you like to see it integrated (since it's not redistributable)?

**Comment by mindthegab** [comment]
Also happy if you want to contribute with a pull request if you guys have Jrebel available and want to test a good configuration to update the existing Jrebel profile.

**Comment by mindthegab** [comment]
Hey @jgoldhammer, any comment / follow up?

**Comment by jgoldhammer** [comment]
I have not made any progress yet... I will test JRebel integration the next weeks. I will close the ticket for now...
