### ISSUE TITLE
Alfresco SDK Module downgrade error

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/alfresco-sdk#346]
Alfresco SDK 2.1.1
Java 1.8
Maven 3.3.3
repo project

When starting the repository (mvn install -Pamp-to-war,enterprise) or running the remote unit tests, I have often the following error:
```
Caused by: org.alfresco.error.AlfrescoRuntimeException: 10170019 
Downgrading of modules is not supported.
Module 'xxx-amp' version 1.0.1511161042 is currently installed and must be uninstalled before version ${noSnapshotVersion} can be installed.
	at org.alfresco.error.AlfrescoRuntimeException.create(AlfrescoRuntimeException.java:51)
	at org.alfresco.repo.module.ModuleComponentHelper.startModule(ModuleComponentHelper.java:632)
	at org.alfresco.repo.module.ModuleComponentHelper.access$500(ModuleComponentHelper.java:61)
	at org.alfresco.repo.module.ModuleComponentHelper$1$1.execute(ModuleComponentHelper.java:259)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:454)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:342)
	at org.alfresco.repo.module.ModuleComponentHelper$1.doWork(ModuleComponentHelper.java:280)
	... 57 more
```
module.properties contains following entry:
```
module.version=${noSnapshotVersion}
```

I have even tried to clean the target directory with
```
mvn clean
```
but it does not help...

Do you have any idea ?

**Comment by jgoldhammer** [comment]
Just noticed that the placeholder ```noSnapshotVersion``` was not replaced. Any idea?

**Comment by gravitonian** [comment]
Hi,

I have tried a repo-amp 2.1.1 SDK project and it works with the following config:

```
$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
Maven home: /home/martin/apps/apache-maven-3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-58-generic", arch: "amd64", family: "unix"
```
And $ mvn clean install -Pamp-to-war 
Tested with enterprise too, no problem.

However, we are removing the module.version=${noSnapshotVersion} and changing to module.version=${project.version}

See: https://issues.alfresco.com/jira/browse/DEVPLAT-452
