### ISSUE TITLE
AOI – run profile does not work with the purge profile.

### ISSUE THREAD

**Issue by manoswerts** [Alfresco/alfresco-sdk#349]
- Create a new All In One project (SDK 2.1.1).
- Run the following command to run Alfresco: `mvn clean install -Prun,enterprise,purge`
- Solr will not start due to the the following exception:

```
org.apache.solr.common.SolrException: Could not load core configuration for core collection1
    at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:554)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:261)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:253)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error loading solr config from /Users/mano/Projects/Test/test/alf_data_dev/solr4/config/collection1/solrconfig.xml
    at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:148)
    at org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:79)
    at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:61)
    ... 9 more
Caused by: java.io.IOException: Can't find resource 'solrconfig.xml' in classpath or '/Users/mano/Projects/Test/test/alf_data_dev/solr4/config/collection1/conf'
    at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:362)
    at org.apache.solr.core.SolrResourceLoader.openConfig(SolrResourceLoader.java:308)
    at org.apache.solr.core.Config.<init>(Config.java:116)
    at org.apache.solr.core.Config.<init>(Config.java:86)
    at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:161)
    at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:144)
    ... 11 more
```

When using the `purge` profile, the `runner` module will delete everything in `alf_data_dev`, including the Solr `config` directory. This is not unpacked again afterwards, causing the failed startup.

_Workaround:_ Copy the plugins from the `solr-config` module to the `runner` module.

**Comment by ohej** [comment]
Can you provide the full output from the log?

**Comment by manoswerts** [comment]
[buildlog.txt](https://github.com/Alfresco/alfresco-sdk/files/43654/buildlog.txt)

**Comment by iarroyo** [comment]
Hi guys.

The issue happens because the purge profile is called after the solr-config is unpacked, so the alf_data_dev directory is removed. The purge profile comes from sdk-parent-pom.xml, and i think it is executed for each module. 

I fixed that issue removing the purge profile from the sdk-parent-pom.xml and including it in the solr-config project.

Now the solr-config remove the alf_data_dev dir and then unpack it correctly. Obviously we need to keep the right order for each module. (which comes from the archetype OOTB)

    <module>repo-amp</module>
    <module>skd-2.2.0-share-amp</module>
    <module>repo</module>
    <module>solr-config</module>
    <module>share</module>
    <module>runner</module>

I dont think it is the best solution, because the solr-config is not the best place to include the purge profile.

Cheers

**Comment by ohej** [comment]
Doing purge and run at the same time will cause this. There is no easy way to fix it the current way. I suggest you do a `mvn clean -Ppurge` before running.
