### ISSUE TITLE
Alfresco SDK archetypies don't compile within eclipse mars.2

### ISSUE THREAD

**Issue by ceeliro** [Alfresco/alfresco-sdk#365]
Hello!

First apologized for not being more specif but don't know where to start... I have googled for one day without success...

issue scenario:
- Ubuntu 15.10
- brand new eclipse mars.2 
- Oracle JDK 8
- maven 3.3.3 (also tried with 3.2.5)
- create maven project -> org.alfresco.maven.archetype:alfresco-allinone-archetype:2.1.1 (also tried with others alfresco SDK archetypes)

Then nothings compiles... Many errors in POMs.xml

Project build error: Unresolveable build extension: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0

org.apache.maven.plugin.PluginManagerException: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0 (org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1:refresh:refresh-webscripts-repo-and-share:process-resources)

java.lang.IllegalStateException: org.apache.maven.plugin.PluginManagerException: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:350)
    at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
    at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
    at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
    at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
    at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
    at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
    at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.plugin.PluginManagerException: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:857)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:344)
    ... 33 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.alfresco.maven.plugin:alfresco-maven-plugin:2.1.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:214)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
    at org.eclipse.m2e.core.internal.project.registry.EclipsePluginDependenciesResolver.resolve(EclipsePluginDependenciesResolver.java:59)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts(DefaultMavenPluginManager.java:940)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm(DefaultMavenPluginManager.java:867)
    at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm(DefaultProjectBuildingHelper.java:196)
    at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultModelBuildingListener.java:111)
    at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatapult.java:44)
    at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:1270)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:437)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:417)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:407)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:161)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$5.call(ProjectRegistryManager.java:815)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$5.call(ProjectRegistryManager.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.execute(ProjectRegistryManager.java:956)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readProjectWithDependencies(ProjectRegistryManager.java:811)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readProjectWithDependencies(ProjectRegistryManager.java:794)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$6.call(ProjectRegistryManager.java:999)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$6.call(ProjectRegistryManager.java:1)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4724)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4721)
    at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.getMavenProject(ProjectRegistryManager.java:997)
    at org.eclipse.m2e.core.internal.project.registry.MavenProjectFacade.getMavenProject(MavenProjectFacade.java:242)
    at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:98)
    ... 17 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.alfresco.maven.plugin:alfresco-maven-plugin:jar:2.1.1 -> org.apache.maven:maven-plugin-api:jar:3.0.4 -> org.sonatype.sisu:sisu-inject-plexus:jar:2.3.0 -> org.sonatype.sisu:sisu-inject-bean:jar:2.3.0 -> org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
    at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:202)
    ... 51 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.sonatype.sisu.inject:guice-bean-containers:jar:2.3.0
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:302)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:218)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
    at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
    ... 53 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer org.sonatype.sisu.inject:guice-bean-containers:pom:2.3.0 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.sonatype.sisu.inject:guice-bean-containers:pom:2.3.0 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:287)
    ... 72 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer org.sonatype.sisu.inject:guice-bean-containers:pom:2.3.0 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.sonatype.sisu.inject:guice-bean-containers:pom:2.3.0 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238)
    at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
    ... 75 more

**Comment by ceeliro** [comment]
It seems to be privileges issue. Running eclipse as sudo works but the thing is that it doesn't happen for other maven project that I have only for alfresco SDK

Thanks anyway

**Comment by jgoldhammer** [comment]
@ceeliro,

have you tried with Alfresco SDK 3? The dependency guide-bean-containers is not an alfresco original dependency, so please try a fresh project to build with Eclipse.

I will close the ticket in 7 days, if there is no reaction.

Thanks
Jens

**Comment by ohej** [comment]
I have not been able to reproduce this issue and we haven't had any updates since November 2016. Feel free to reopen or raise a new issue if this is still the case with SDK3
