### ISSUE TITLE
RAD unavailable in 2.1.1 and 2.2.0 projects

### ISSUE THREAD

**Issue by alex4u2nv** [Alfresco/alfresco-sdk#371]
Tried with AIO and single repo amp, tested different versions of Java, windows/mac, and intellij/eclipse
For the Single Repo Amp, the following error is returned:
java.lang.RuntimeException: Unable to send request to http://localhost:4578/ecm.behavior.test.ImmutableBehaviorTest?method=testImmutableBehavior&runner=org.springframework.test.context.junit4.SpringJUnit4ClassRunner: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 ecm.behavior.test.ImmutableBehaviorTest</title>
</head>
<body>

<h2>HTTP ERROR: 500</h2>

<p>Problem accessing /ecm.behavior.test.ImmutableBehaviorTest. Reason:
<pre>   ecm.behavior.test.ImmutableBehaviorTest</pre></p>

<hr /><i><small>Powered by Jetty://</small></i>

</body>
</html>

```
at com.tradeshift.test.remote.internal.InternalRemoteRunner.handleError(InternalRemoteRunner.java:189)
at com.tradeshift.test.remote.internal.InternalRemoteRunner.runChild(InternalRemoteRunner.java:143)
at com.tradeshift.test.remote.internal.InternalRemoteRunner.runChild(InternalRemoteRunner.java:41)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

Any thoughts or workarounds available?

**Comment by alex4u2nv** [comment]
2.1.0 Seems to work for now.

**Comment by alex4u2nv** [comment]
Traced down the issue to be because of ClassLoader that is being passed to the RemoteServer and SpringJUnit4ClassRunner

**Comment by ohej** [comment]
We have a whole new approach to integration testing with SDK3 which seems to be much more reliable. Closing this issue
