### ISSUE TITLE
Cannot run "share-amp-archetype" project

### ISSUE THREAD

**Issue by badluck1024** [Alfresco/alfresco-sdk#415]
Since few days I can not run any "share-amp-archetype" project with alfresco-sdk 3.0.0-beta-4 version. The issue is due to this error: **Invalid database configuration, use enableH2, enableMySQL, enablePostgreSQL, or enabaleEnterpriseDb**

```
### `[INFO] Using 'UTF-8' encoding to copy filtered resources.
[DEBUG] resource with targetPath null
directory src/test/properties/${env}
excludes []
includes [**]
[INFO] skip non existing resourceDirectory C:\Users\Alessandro\git\alfsol-dharma\dharma-email-viewer-share\src\test\properties\${env}
[DEBUG] no use filter components
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.151 s
[INFO] Finished at: 2016-09-29T20:10:35+02:00
[INFO] Final Memory: 42M/1202M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0-beta-4:run (default-cli) on project dharma-email-viewer-share: Invalid database configuration, use enableH2, enableMySQL, enablePostgreSQL, or enabaleEnterpriseDb -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0-beta-4:run (default-cli) on project dharma-email-viewer-share: Invalid database configuration, use enableH2, enableMySQL, enablePostgreSQL, or enabaleEnterpriseDb
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Invalid database configuration, use enableH2, enableMySQL, enablePostgreSQL, or enabaleEnterpriseDb
    at org.alfresco.maven.plugin.RunMojo.renameAlfrescoGlobalProperties(RunMojo.java:507)
    at org.alfresco.maven.plugin.RunMojo.execute(RunMojo.java:270)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`
```

**Comment by badluck1024** [comment]
The issue is due to RunMojo class into the renameAlfrescoGlobalProperties method. It seems that the method does not bother to manage startup of share with the property enableH2 setted to false. A possible workaround to this issue is to set the property **enableTestProperties** to **false** into the configuration section of the alfresco-maven-plugin into "share-amp-archetype" project pom.


                <configuration>

                    <alfrescoEdition>community</alfrescoEdition>

                    
                    <enableH2>false</enableH2>
                    <enablePlatform>false</enablePlatform>
                    <enableSolr>false</enableSolr>

					<enableTestProperties>false</enableTestProperties>
                    
                    <enableShare>true</enableShare>

                    
                    <shareModules>
                        <moduleDependency>
                            
                            <groupId>${alfresco.groupId}</groupId>
                            <artifactId>aikau</artifactId>
                            <version>${aikau.version}</version>
                        </moduleDependency>
                        
                        <moduleDependency>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>${project.artifactId}</artifactId>
                            <version>${project.version}</version>
                        </moduleDependency>
                    </shareModules>
                </configuration>

**Comment by gravitonian** [comment]
Should be fixed now if building SDK 3.0 from SNAPSHOT

**Comment by jgoldhammer** [comment]
@ohej 
Can you please push a new version of the sdk into alfresco artifacts? 
Currently it is not possible to create and run a share project without getting this error...

Thanks
Jens

**Comment by jpotts** [comment]
+1 this is still broken. The workaround from @badluck1024 seems to fix it.

**Comment by ohej** [comment]
I've just verified that this issue is fixed: The Share JAR Archetype works out of the box now
