### ISSUE TITLE
After switching from 5.2-EA to 5.1.1 enterprise « hotswap » did not worked anymore.

### ISSUE THREAD

**Issue by pdubois** [Alfresco/alfresco-sdk#421]
After switching from 5.2-EA to 5.1.1 enterprise « hotswap » did not worked anymore.
Every time class is modified, it thows following error:
/local/eclipse/projects/aio2/aio2-platform-jar/target/classes/org/alfresco/test2/platformsample/HelloWorldWebScript.class for event ENTRY_MODIFY
HOTSWAP AGENT: 14:33:11.255 DEBUG (org.hotswap.agent.plugin.hotswapper.HotswapperPlugin) - Class org.alfresco.test2.platformsample.HelloWorldWebScript will be reloaded from URL file:/usr/local/eclipse/projects/aio2/aio2-platform-jar/target/classes/org/alfresco/test2/platformsample/HelloWorldWebScript.class
HOTSWAP AGENT: 14:33:11.454 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing pluginManager.hotswap([class org.alfresco.test2.platformsample.HelloWorldWebScript])
HOTSWAP AGENT: 14:33:11.455 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [org.alfresco.test2.platformsample.HelloWorldWebScript] (autoHotswap)
Exception in thread "Thread-84" java.lang.IllegalStateException: Unable to redefine classes
	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:271)
	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:268)
	... 2 more

Note:
I did not changed superclass or interface and it was working fine with 5.2-EA version.

Attached my pom and the logs.

**Comment by pdubois** [comment]
Attached here the logs and the pom.xml 
[Documents.zip](https://github.com/Alfresco/alfresco-sdk/files/539552/Documents.zip)

**Comment by ohej** [comment]
I haven't been able to reproduce this issue, @pdubois can you retest with the latest version?
