### ISSUE TITLE
Nullpointer in code crashes Freemarker evaluation within Integration Testing

### ISSUE THREAD

**Issue by nklomp** [Alfresco/alfresco-sdk#478]
## I'm submitting a ...   (check one with "x")
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request

A nullpointer in an Integration tests causes an error in Freemarker evaluation because the error message will be null and the template is not designed to handle this case. This could confuse the developer, because the integration test ends with an error like below, instead of a message about the nullpointer.

This is caused by the fact that message of JUnit's Failure class delegates to getMessage() of the throwable which can be null in some cases (Nullpointer for instance) causing the Freemarker template evaluation to fail which in turn hides the real problem in the integration test.

## Expected Behavior
Show the real problem to the developer: The nullpointer exception

## Current Behavior
```

Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> failure.getMessage()  [in template "org/alfresco/rad/test/runtest.get.xml.ftl" at line 10, column 24]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction:
==> ${failure.getMessage()?html}  [in template "org/alfresco/rad/test/runtest.get.xml.ftl" at line 10, column 22]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:98)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:382)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.StringBuiltins$StringBuiltIn._eval(StringBuiltins.java:87)
        at freemarker.core.Expression.eval(Expression.java:111)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:115)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:193)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:509)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:103)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:286)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:86)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.MixedContent.accept(MixedContent.java:93)
        at freemarker.core.Environment.visit(Environment.java:265)
        at freemarker.core.Environment.process(Environment.java:243)
        at org.alfresco.repo.template.FreeMarkerProcessor.process(FreeMarkerProcessor.java:230)
        ... 35 more
```

## Possible Solution
See PR https://github.com/Alfresco/alfresco-sdk/pull/477

## Steps to Reproduce (for bugs)
Just generate an intentional nullpointer in code called from the integration test

## Context
IT test on different platforms

## Your Environment

* Alfresco SDK version used: 3.0.1

**Comment by marsv024** [comment]
My PR contains the same fix. #472

**Comment by nklomp** [comment]
Hi Marcus,

Sorry I looked for duplicates, but apparently not good enough ;-)

There is however a difference between your PR and mine. Your' s makes everything null safe, which I think could hide problems related directly to the code that calls the template. If I remember the code correctly every var in the freemarker template should be filled by the code, except for the message part which can be null in some cases (nullpointer).

**Comment by marsv024** [comment]
Hi Niels,

No problem, I noticed I only created a PR and not any issue related to it when submitting my proposed fix.

As for the difference in our PR's, I guess you may be right on that point, I might have been a bit eager in my code to make things null safe. I'll leave it to @ohej or other in the team to decide which approach to use.

As long as this issue is fixed I'm happy :)

/Marcus

**Comment by nklomp** [comment]
PR #477 was merged. Thx
