### ISSUE TITLE
java.util.MissingResourceException: Can't find bundle for base name alfresco.web-extension.messages.*

### ISSUE THREAD

**Issue by angelborroy-ks** [Alfresco/alfresco-sdk#497]
## I'm submitting a ...   (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

## Expected Behavior
When using `run.sh` on default `alfresco-share-jar-archetype` project, it should work.

## Current Behavior
Share web application does not start due to missing resources in classpath:

```
2018-04-13 19:42:01,378  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
java.util.MissingResourceException: Can't find bundle for base name alfresco.web-extension.messages.test-share, locale en_ES
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.springframework.extensions.surf.util.I18NUtil.getLocaleProperties(I18NUtil.java:468)
```

However, it works properly when:

* It's packaged and deployed to Alfresco installation
* Hotswap configuration file is removed: `/test-share/src/test/resources/share-hotswap-agent.properties`

## Steps to Reproduce (for bugs)
```
$ mvn archetype:generate -Dfilter=org.alfresco:

Choose archetype:
1: remote -> org.alfresco.maven.archetype:activiti-jar-archetype
2: remote -> org.alfresco.maven.archetype:alfresco-allinone-archetype
3: remote -> org.alfresco.maven.archetype:alfresco-amp-archetype
4: remote -> org.alfresco.maven.archetype:alfresco-platform-jar-archetype
5: remote -> org.alfresco.maven.archetype:alfresco-share-jar-archetype
6: remote -> org.alfresco.maven.archetype:share-amp-archetype

Choose a number or apply filter (format: ...): : 5

Choose org.alfresco.maven.archetype:alfresco-share-jar-archetype version:
1: 3.0.0
2: 3.0.1
Choose a number: 2

Define value for property 'groupId': : es.keensoft
Define value for property 'artifactId': : test-share
Define value for property 'package':  es.keensoft: :
 Y: : Y

$ cd test-share
$ chmod +x run.sh
$ ./run.sh
```

## Context
I was preparing learning material for next week. Just trying to follow Alfresco Docs instructions.

## Your Environment
* Alfresco SDK version used: 3.0.1
* Alfresco version used: None
* Output of command 'mvn -version': 
```
HOTSWAP AGENT: 19:49:42.952 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.2.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 19:49:43.429 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish]
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /usr/local/Cellar/maven/3.5.3/libexec
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: en_ES, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
``` 
* Link to your project: Just default project created by archetype without modifications.

**Comment by angelborroy-ks** [comment]
In my case the problem was due to using Hotswap 1.2.0, it works with 1.0
