### ISSUE TITLE
Failed to read Cyrillic dictionary after an upgrade to Alfresco 7.0.0 from 6.2

### ISSUE THREAD

**Issue by iva-nova-e-katerina** [Alfresco/alfresco-sdk#618]
Hi!

I have an installation of Alfresco 6.2  on development environment which was perfomed using SDK 4.x and there is a lot of custom code here. When I upgrading this Alfresco installation according following guide https://github.com/Alfresco/alfresco-sdk/blob/master/docs/advanced-topics/switching-versions.md to  version 7.0.0
I got warning :
```

Step 8/15 : RUN java -jar $TOMCAT_DIR/alfresco-mmt/alfresco-mmt*.jar install $TOMCAT_DIR/amps $TOMCAT_DIR/webapps/alfresco -directory -nobackup -force ---> Running in e2c4ca6f376d /
bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) 
```

then I got error  while reading Cyrillic named dictionary:

```
Exception in thread "main" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: ?????? ???.xml
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.nio.file.Path.resolve(Path.java:515)
        at de.schlichtherle.truezip.fs.nio.file.FileEntry.<init>(FileEntry.java:60)
        at de.schlichtherle.truezip.fs.nio.file.FileController.getOutputSocket(FileController.java:172)
        at de.schlichtherle.truezip.file.TBIO.getOutputSocket(TBIO.java:311)
        at de.schlichtherle.truezip.file.TBIO.cp0(TBIO.java:218)
        at de.schlichtherle.truezip.file.TBIO.cp_r0(TBIO.java:179)
        at de.schlichtherle.truezip.file.TBIO.cp_r0(TBIO.java:169)
        at de.schlichtherle.truezip.file.TBIO.cp_r0(TBIO.java:169)
        at de.schlichtherle.truezip.file.TBIO.cp_r0(TBIO.java:169)
        at de.schlichtherle.truezip.file.TBIO.cp_r0(TBIO.java:169)
        at de.schlichtherle.truezip.file.TBIO.cp_r(TBIO.java:138)
        at de.schlichtherle.truezip.file.TFile.cp_rp(TFile.java:3188)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModule(ModuleManagementTool.java:268)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:172)
        at org.alfresco.repo.module.tool.ModuleManagementTool.installModules(ModuleManagementTool.java:155)
        at org.alfresco.repo.module.tool.ModuleManagementTool.main(ModuleManagementTool.java:837)
ERROR: Service 'ndfund-acs' failed to build: The command '/bin/sh -c java -jar $TOMCAT_DIR/alfresco-mmt/alfresco-mmt*.jar install               $TOMCAT_DIR/amps $TOMCAT_DIR/webapps/alfresco -directory -nobackup -force' returned a non-zero code: 1

```

Also I got the same Exception when created Alfresco 7.0.0 project from the scratch (then copied custom files there) and  same message rises when I login to running ACS container :
```

docker exec -it 538006db08a9 /bin/bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

I beleive that it is because of upgrade CentOS from version 7 to version 8 for ACS container, and I have fixed this issue by adding:
`RUN yum -y install glibc-locale-source glibc-langpack-en`
to the <project>-platform-docker/src/main/docker/Dockerile

**Comment by andrea-ligios** [comment]
For licensing reasons, all our images are now based on CentOS 7, not anymore on CentOS 8 (that will be out of support at the end of 2021).

I'm glad you've solved the problem on your own, but feel free to test it again when ACS 7.1 and SDK 4.3 will be out and comment here on the results. 

If the problem was related to CentOS 8, it should work out of the box again.

Thank you
